- name: Install winpcap via nmap using choco
  win_chocolatey:
    name: nmap
    version: 7.12

- name: Ensure empty output directory
  win_file:
    path:  "{{ workdir }}\\output"
    state: absent

- name: Replace configuration file (windows)
  win_copy:
    src:  "{{ beat_name }}.yml"
    dest: "{{ installdir }}\\{{ beat_name }}.yml"

- name: Install {{ beat_name | capitalize }} service
  win_shell: "{{ installdir }}\\install-service-{{ beat_name }}.ps1"

- name: Start {{ beat_name | capitalize }} service
  win_service:
    name:  "{{ beat_name }}"
    state: started

- name: Sleep a little
  win_shell: Start-Sleep -s 1

- name: curl google.com
  win_get_url:
    url:  'http://google.com'
    dest: 'c:\test-temp.file'

- name: Sleep a little
  win_shell: Start-Sleep -s 3

- name: Stop {{ beat_name | capitalize }} service
  win_service:
    name:  "{{ beat_name }}"
    state: stopped

- name: Uninstall {{ beat_name | capitalize }} service
  win_shell: "{{ installdir }}\\uninstall-service-{{ beat_name }}.ps1"

- name: Stat output file
  win_stat:
    path: "{{ workdir }}\\output\\{{ beat_name }}"
  register: output_stat

- debug: var=output_stat

- name: Check output file
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 800"
