---

# The default registry file path changed with 7.0.
registry_file: '{{ "registry/filebeat/data.json" if version is version_compare("7.0", ">=") else "registry" }}'
filebeat_logs_dir: '{{ ansible_user_dir }}/filebeat_logs'
