- name: Ensure empty output directory
  win_file:
    path:  "{{ workdir }}\\output"
    state: absent

- name: Replace configuration file (windows)
  win_copy:
    src: "{{ beat_name }}.yml"
    dest: "{{ installdir }}\\{{ beat_name }}.yml"

- name: Install {{ beat_name | capitalize }} service
  win_shell: "{{ installdir }}\\install-service-{{ beat_name }}.ps1"

- name: Start {{ beat_name | capitalize }}
  win_service:
    name:  "{{beat_name}}"
    state: started

- name: Sleep a little
  win_shell: Start-Sleep -s 10

- name: Stop {{ beat_name | capitalize }}
  win_service:
    name:  "{{ beat_name }}"
    state: stopped

- name: Uninstall {{ beat_name | capitalize }} service
  win_shell: "{{ installdir }}\\uninstall-service-{{ beat_name }}.ps1"

- name: Stat output file
  win_stat:
    path: "{{ workdir }}\\output\\{{ beat_name }}"
  register: output_stat

- debug: var=output_stat

- name: Check output file
  assert:
    that:
      - "output_stat.stat.exists"
      - "output_stat.stat.size > 250"
